{% set name = "django-revproxy" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jazzband/django-revproxy/archive/{{ version }}.tar.gz
  sha256: 2a568e5b18f522c07bcc34c4ee05a41a63fdbfdca014284ab8a56bee102f47e6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django >=3.0
    - urllib3 >=1.12
  run_constrained:
    - diazo >=1.0.5
    - lxml >=3.4,<3.5

test:
  imports:
    - revproxy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jazzband/django-revproxy
  summary: Reverse Proxy view that supports all HTTP methods, Diazo transformations and Single Sign-On.
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
